title: Jake Hansen Technology
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7244898
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#0F050C'
    - '#4B4B5C'
    - '#FFF2CF'
    - '#991F20'
    - '#C516A3'
  rhythmicContrast: 0.2787325
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Jakehansen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6718582
layout_spectrum: 1
