name: Jakehansen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09265
title: Jake Hansen Technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0A070C'
    - '#FFFAE9'
    - '#5C5C4B'
    - '#F2CF77'
    - '#20BC92'
  brandStrength: 0.9779807
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.1387153
purpose: []
