layout_spectrum: 1
color:
  saturation: 0.6546724
  lightness: 1
  brandStrength: 0.9779807
  brandColors:
    - '#0A070C'
    - '#FFFAE9'
    - '#5C5C4B'
    - '#F2CF77'
    - '#20BC92'
  rhythmicContrast: 0.1387153
typography_spectrum: 0.1186896
name: Jakehansen
